#! /usr/bin/env node
const crawler = require('./src/events/crawler/index.js')
const scraper = require('./src/events/scraper/index.js')
const regenerator = require('./src/scheduled/regenerate/index.js')

const args = require('./src/cli/args.js')
const makeNice = require('./src/cli/make-nice.js')

let { date } = args
let { source, crawl, scrape, regenerate } = makeNice(args)

;(async () => {
  // TODO add warning about sandbox not being started here

  if (crawl) {
    await crawler({ source: crawl })
  }
  if (scrape) {
    await scraper({ source: scrape, date })
  }
  if (regenerate) {
    await regenerator({ source })
  }
})()
