#! /usr/bin/env node
require('./src/cli/env.js')()
const args = require('./src/cli/args.js')
const makeNice = require('./src/cli/make-nice.js')
const arc = require('@architect/functions')

const runReport = require('./src/scheduled/report/index.js').handler
const timeseriesRegenerator = require('./src/scheduled/regen-timeseries/index.js').handler
const taskRunner = require('./src/scheduled/runner/index.js').handler

let { date, utc } = args
let { crawl, scrape, regenerate, regenTimeseries, report, runner } = makeNice(args)

;(async () => {
  if (crawl) {
    await arc.events.publish({
      name: 'crawler',
      payload: {
        source: crawl
      }
    })
  }
  if (scrape) {
    await arc.events.publish({
      name: 'scraper',
      payload: {
        date,
        source: scrape,
        _useUTCdate: utc
      }
    })
  }
  if (regenerate) {
    console.log(`⚠️  About to regenerate ${regenerate}, you've got 3 seconds to cancel!`)
    setTimeout(async () => {
      await arc.events.publish({
        name: 'regenerator',
        payload: {
          date,
          source: regenerate
        }
      })
    }, 3000)
  }
  if (report) {
    await runReport()
  }
  if (regenTimeseries) {
    await timeseriesRegenerator()
  }
  if (runner) {
    await taskRunner()
  }
})()
